# =============================================================================
# technical_output.py -- Auto-generated by export_for_lca.py
# Do not edit manually. Re-run export_for_lca.py to update.
# Generated on: 2026-06-13 18:18:39
# =============================================================================

# --- General Information ---
N_TURBINES              = 34
MW_PER_TURBINE          = 22.0
TOTAL_FARM_SIZE_MW      = 748.0
CAPACITY_FACTOR         = 0.53
DISTANCE_TO_SHORE_KM    = 110.0
PORT_DISTANCE_CTV_KM = 30.0
PORT_DISTANCE_HLV_KM = 100.0
PORT_DISTANCE_FSV_KM = 50.0
LIFETIME_YEARS          = 20
ENERGY_NET_KWH          = 6.9456e+10

# --- Component Masses (tonnes) ---
PITCH_BEARING_MASS_KG            = 95646.7

# 1.1 Hub System (Rotor)
TURBINE_HUB_STEEL_T              = 118.0
TURBINE_HUB_GLASS_FIBER_T        = 3.0

# 1.2 Blades (Rotor)
TURBINE_BLADES_T                 = 246.903  # split: Glass Fibre = TURBINE_BLADES_T * 0.40 | Epoxy = TURBINE_BLADES_T * 0.60

# 1.3 Main Shaft and Bearings
TURBINE_MAIN_SHAFT_STEEL_T       = 59.1

# 1.4 Generator
TURBINE_GENERATOR_NDFEB_T        = 25.2
TURBINE_GENERATOR_COPPER_T       = 17.1
TURBINE_GENERATOR_ELEC_STEEL_T   = 105.6
TURBINE_GENERATOR_STEEL_T        = 357.09

# 1.5 Brake
TURBINE_BRAKE_STEEL_T            = 39.2

# 1.6 Turret (Nacelle)
TURBINE_TURRET_STEEL_T           = 6.0

# 1.7 Bedplate (Nacelle)
TURBINE_BEDPLATE_STEEL_T         = 75.1

# 1.8 Yaw System (Nacelle)
TURBINE_YAW_STEEL_T              = 37.5

# 1.9 Nacelle Cover and Platforms
TURBINE_NACELLE_STEEL_T          = 41.4
TURBINE_NACELLE_COMPOSITE_T      = 17.8

# 1.10 HVAC and Auxiliaries
TURBINE_HVAC_T                   = 12.8
TURBINE_CABLING_T                = 4.0  # split: Copper = 2.6 t | Plastic = 1.4 t
TURBINE_LUBE_HYDRAULICS_T        = 2.5

# 1.11 Converter
TURBINE_CONVERTER_T              = 17.4

# 1.12 Transformer
TURBINE_TRANSFORMER_T            = 44.0

# 1.13 Tower
TURBINE_TOWER_STEEL_T            = 1574.0
TURBINE_TOWER_TOP_STEEL_T        = 8.0

# 2.1 Monopile
SUBSTRUCTURE_MONOPILE_STEEL_T    = 2097.0

# 2.2 Transition Piece
SUBSTRUCTURE_TRANSITION_STEEL_T  = 100.0

# --- O&M Interventions (average per year, mode_id == 3) ---
N_INTERVENTIONS = {
    "power_converter":           58.721934,
    "electrical_system":         1.525591,
    "hydraulic_pitch_system":    0.706549,
    "yaw_system":                0.706549,
    "rotor_blades":              0.889081,
    "generator":                 6.865150,
    "drive_train":               7.411686,
}

# --- Vessel Hours (expected over operational lifetime) ---
VESSEL_HOURS_BY_TYPE = {
    "CTV":                       48925.59,
    "LCN":                       30914.33,
}
