name: winpact
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - ipykernel
  - nbformat>=4.2.0

  # core scientific stack from conda
  - numpy
  - scipy
  - pandas
  - matplotlib
  - pyarrow
  - pyyaml
  - numpy-financial

  # avoid pip builds for netcdf stack
  - netcdf4
  - h5py
  - cftime
  - xarray

  - pip:
      - astral==3.2
      - attr==0.3.2
      - attrs==25.4.0
      - plotly==6.0.1
      - py_wake==2.6.11
      - windio==2.0.1
