from __future__ import annotations

"""
OPEX module – scaffolding for three calculation modes:
  1) 'capex_fraction' – existing behaviour: OpEx as a fraction of CapEx
  2) 'analytic_ctmc' – analytical CTMC expectations (availability, expected counts, OpEx)
  3) 'time_march_ctmc' – event/time-marching CTMC (availability time series + activity log)

This file contains only structure and dummy implementations. Replace TODOs with real logic.

External integration points expected (per existing project):
  - ValueWindEnv (env): provides metocean, calendar, config accessors
  - WindFarm (wf): provides power_records (pd.DataFrame), turbines inventory, farm meta

Keep the public surface compatible with the current code:
  - class OPEX with method calc_OPEX(self) -> dict of artefacts including 'OPEX_records'

Author: scaffolding generated by ChatGPT
"""

from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple, Literal, Any
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import math

from core.File_Handling import load_yaml, process_duration_fields
from core.utils import apply_overrides , get_input_parameter


# -----------------------------------------------------------------------------
# Data contracts (schemas) – light, minimal versions
# -----------------------------------------------------------------------------

@dataclass
class VesselSpec:
    # Identity / type
    name: str
    capability: str = "CTV"  # class/type label as given in input (e.g., "CTV", "SOV")

    # Ops limits (weather gating)
    Hs_limit_m: float = 1.5                  # from max_waveheight
    wind_limit_ms: Optional[float] = None    # from max_windspeed

    # Transit & logistics
    speed_kn: float = 20.0                   # derived from YAML 'speed' (assumed km/h) -> knots
    base_distance_km: float = 0.0            # from port_distance
    strategy: Literal["scheduled","spot","permanent","campaign","unspecified"] = "unspecified"

    # Costing
    day_rate_eur: float = 0.0                # from equipment_rate
    mobilization_fee_eur: float = 0.0        # from mobilization_cost
    mobilization_days: float = 0.0           # from mobilization_days

    # Optional extras (placeholders for future use)
    crew_capacity: Optional[int] = None
    availability_fraction: float = 1.0


@dataclass
class PMPolicy:
    type: Literal["interval", "reliability", "none"] = "none"
    tau_h: Optional[float] = None  # for 'interval'
    xi_PM: Optional[float] = None  # for 'reliability'

@dataclass
class MaintenanceSpec:
    """
    One maintenance “mode” entry, either a CM failure mode or a PM task.
    - For CM entries, lambda_per_h > 0 and task_type == "CM".
    - For PM entries, lambda_per_h == 0 and task_type == "PM" (use frequency_per_year or tau_h).
    """
    component: str                      # e.g., "electrical_system"
    mode_id: Optional[str]              # e.g., "1", "2" for failures; "PM:0" for maintenance[0]
    task_type: Literal["CM", "PM"]
    # Stochastic/tempo
    lambda_per_h: float                 # CM failure rate per hour; 0 for PM
    shape: Optional[float] = None       # Weibull shape (CM only, if provided)
    scale_years: Optional[float] = None # Weibull scale in years (CM only, if provided)
    frequency_per_year: Optional[float] = None # PM only; if set, tau_h = 8760/freq
    tau_h: Optional[float] = None       # PM interval hours (derived from frequency if provided)
    # Durations & costs
    MTTR_h: float = 0.0                 # duration for the task (CM or PM)
    spares_eur: float = 0.0
    labour_rate_eur_h: float = 80.0
    labour_h: float = 0.0               # default to MTTR_h (1-tech equivalent) unless you model crew size
    preferred_vessels: List[str] = field(default_factory=list)
    description: Optional[str] = None


@dataclass
class AccessProfile:
    task_type: Literal["CM", "PM"]
    mu_A_per_h: float  # access rate (1/MTTW)
    mu_R_per_h: float  # repair productivity (1/MTTR_effective)
    service_time_h: float  # total service time incl. transits
    chosen_vessels: List[str] = field(default_factory=list)

@dataclass
class ActivityLogEntry:
    timestamp_start: pd.Timestamp
    timestamp_end: pd.Timestamp
    turbine_id: str
    component: str
    task_type: Literal["CM", "PM"]
    vessels: List[str]
    sailing_h: float
    onsite_h: float
    crew_h: float
    spares_eur: float
    labour_eur: float
    transport_eur: float
    total_cost_eur: float

@dataclass
class AvailabilitySummary:
    component_A: Dict[str, float]  # per component availability (0..1)
    turbine_A: Dict[str, float]    # per turbine availability
    farm_A: float                  # farm availability
    downtime_h: Dict[str, float]   # per component downtime over horizon

@dataclass
class OpExBreakdown:
    fixed_OM_eur: float
    CM_cost_eur: float
    PM_cost_eur: float
    transport_eur: float
    labour_eur: float
    spares_eur: float

# -----------------------------------------------------------------------------
# OPEX Engine – three modes
# -----------------------------------------------------------------------------

class OPEX:
    def __init__(self, env):
        self.config = env.config
        self.env = env  # Access to simulation environment
        self.parameters = load_OMData(env.config)
        self.parameters =  get_input_parameter(self.parameters, 'OM')

        # Mode selection: 'capex_fraction' (default for backward compat), 'analytic_ctmc', 'time_march_ctmc'
        self.mode = get_input_parameter(self.parameters,'OM_Process', 'Simulation_Mode')
        self.OM_input_file = get_input_parameter(self.parameters,'OM_Process', 'OM_input_file')
        self.OM_vessel_input_file = get_input_parameter(self.parameters,'OM_Process', 'OM_Vessel_input_file')

        self.project_start = pd.to_datetime(
            self.env.config.Project_StartDate,
            format="%d.%m.%Y"
        )

        self.OPEX_records = {}


    # --------------------------- Entry point ---------------------------
    def calc_OPEX(self) -> Dict[str, Any]:
        """Compute OpEx artefacts according to selected mode.
        Returns a dict with at least:
          - 'OPEX_records': pd.DataFrame[timestamp, OM_payment]
          - 'availability_summary': AvailabilitySummary (analytic/time-march), if available
          - 'availability_profile': pd.DataFrame[timestamp, availability] (time-march), if available
          - 'activity_log': pd.DataFrame (time-march), if available
        """
        mode = self.mode
        if mode == "capex_fraction":
            self.Opex_records = self._calc_opex_as_fraction_of_capex()
            return None
        elif mode == "analytic_ctmc":
            self.Opex_records = self._calc_opex_analytic_ctmc()
            return None
        elif mode == "time_march_ctmc":
            self.Opex_records = self._calc_opex_time_march()
            return None

    # --------------------------- Shared helpers (stubs) ---------------------------
    def _load_maintenance_specs(self) -> List[MaintenanceSpec]:
        """
        Parse O&M YAML into a list of MaintenanceSpec where each failure mode (CM)
        and each maintenance entry (PM) becomes one independent item.

        Expected YAML (example):
        Turbine:
        electrical_system:
            name: electrical_system
            maintenance:
            - time: 0
                materials: 0
                service_equipment: CTV
                frequency: 0
            failures:
            1:
                scale: 1.859
                shape: 1
                MTTR: 14
                materials: 1000
                service_equipment: CTV
                description: ...
            2:
                ...

        Assumptions:
        - Weibull scale is in YEARS; shape=k (k=1 exponential). MTBF = scale * Γ(1 + 1/k).
        λ_year = 1/MTBF, λ_per_h = λ_year/8760.
        - PM frequency is events per year; tau_h = 8760 / frequency (if frequency > 0).
        - Labour hours default to MTTR_h at 1 tech equivalent; labour rate from parameters or 80 €/h.
        """
        # Try to load the file the config points to
        try:
            om_data = load_yaml(self.config.valuewind_inputFolder, self.OM_input_file)
        except Exception as e:
            print(f"[OPEX] Could not load OM input file '{self.OM_input_file}': {e}")
            return []

        turbine_block = (om_data or {}).get("Turbine", {})
        if not isinstance(turbine_block, dict) or not turbine_block:
            print("[OPEX] OM input has no 'Turbine' block or it is empty.")
            return []

        # Labour rate from parameters (fallback 80 €/h)
        try:
            labour_rate = float(get_input_parameter(self.parameters, "OM_Costs", "labour_rate_eur_h"))
        except Exception:
            labour_rate = 80.0

        specs: List[MaintenanceSpec] = []

        for comp_key, comp_data in turbine_block.items():
            if not isinstance(comp_data, dict):
                continue
            comp_name = comp_data.get("name", comp_key)

            # ---------- Failures -> CM entries ----------
            failures = comp_data.get("failures", {}) or {}
            for mode_id, f in failures.items():
                if not isinstance(f, dict):
                    continue

                shape = float(f.get("shape", 1.0))
                scale_years = float(f.get("scale", 1.0))
                mttr_h = float(f.get("MTTR", 8.0))
                materials_eur = float(f.get("materials", 0.0))
                vessel = f.get("service_equipment")
                desc = f.get("description")

                # Compute λ_per_h from Weibull mean
                try:
                    mtbf_years = scale_years * math.gamma(1.0 + 1.0 / max(shape, 1e-9))
                except ValueError:
                    mtbf_years = scale_years
                rate_per_year = (1.0 / mtbf_years) if mtbf_years > 0 else 0.0
                lambda_per_h = rate_per_year / 8760.0

                preferred_vessels = [vessel] if vessel else ["CTV"]

                specs.append(
                    MaintenanceSpec(
                        component=comp_name,
                        mode_id=str(mode_id),
                        task_type="CM",
                        lambda_per_h=lambda_per_h,
                        shape=shape,
                        scale_years=scale_years,
                        frequency_per_year=None,
                        tau_h=None,
                        MTTR_h=mttr_h,
                        spares_eur=materials_eur,
                        labour_rate_eur_h=labour_rate,
                        labour_h=mttr_h,
                        preferred_vessels=preferred_vessels,
                        description=desc,
                    )
                )

            # ---------- Maintenance -> PM entries ----------
            maint_list = comp_data.get("maintenance", []) or []
            for i, m in enumerate(maint_list):
                if not isinstance(m, dict):
                    continue
                freq_per_year = float(m.get("frequency", 0.0) or 0.0)
                time_h = float(m.get("time", 0.0) or 0.0)
                materials_pm = float(m.get("materials", 0.0) or 0.0)
                vessel_pm = m.get("service_equipment")
                desc_pm = m.get("description")

                tau_h = (8760.0 / freq_per_year) if freq_per_year > 0 else None
                preferred_vessels_pm = [vessel_pm] if vessel_pm else ["CTV"]

                specs.append(
                    MaintenanceSpec(
                        component=comp_name,
                        mode_id=f"PM:{i}",
                        task_type="PM",
                        lambda_per_h=0.0,
                        shape=None,
                        scale_years=None,
                        frequency_per_year=freq_per_year if freq_per_year > 0 else None,
                        tau_h=tau_h,
                        MTTR_h=time_h,
                        spares_eur=materials_pm,
                        labour_rate_eur_h=labour_rate,
                        labour_h=time_h,
                        preferred_vessels=preferred_vessels_pm,
                        description=desc_pm,
                    )
                )

        return specs



    def _load_vessels(self, *args, **kwargs) -> Dict[str, VesselSpec]:
        """
        Load vessels from the same OM input file the class already points to.
        Expected YAML structure:

        Vessels:
        CTV:
            equipment_rate: 3500          # €/day
            capability: CTV
            speed: 37.04                  # assumed km/h (≈ 20 kn)
            strategy: scheduled
            max_windspeed: 99             # m/s (or sentinel), optional
            max_waveheigh: 2              # typo variant supported
            max_waveheight: 2
            mobilization_cost: 0
            mobilization_days: 0
            port_distance: 30             # km

        Returns a dict: {vessel_name: VesselSpec}
        """
        try:
            vessel_data = load_yaml(self.config.valuewind_inputFolder, self.OM_vessel_input_file)
        except Exception as e:
            print(f"[OPEX] Could not load Vessel input file '{self.OM_vessel_input_file}' for vessels: {e}")
            # Minimal sensible defaults to keep model running
            return {
                "CTV": VesselSpec(name="CTV", capability="CTV", Hs_limit_m=1.5, wind_limit_ms=None,
                                speed_kn=25.0, base_distance_km=40.0, strategy="unspecified",
                                day_rate_eur=15000.0, mobilization_fee_eur=0.0, mobilization_days=0.0)
            }

        vessels_block = (vessel_data or {}).get("Vessels", {})
        if not isinstance(vessels_block, dict) or not vessels_block:
            print("[OPEX] Vessel input has no 'Vessels' block or it is empty; returning default CTV.")
            return {
                "CTV": VesselSpec(name="CTV", capability="CTV", Hs_limit_m=1.5, wind_limit_ms=None,
                                speed_kn=25.0, base_distance_km=40.0, strategy="unspecified",
                                day_rate_eur=15000.0, mobilization_fee_eur=0.0, mobilization_days=0.0)
            }

        out: Dict[str, VesselSpec] = {}
        for v_name, v_data in vessels_block.items():
            if not isinstance(v_data, dict):
                continue

            # Pull with robust defaults
            equipment_rate = float(v_data.get("equipment_rate", 0.0) or 0.0)
            capability = str(v_data.get("capability", "CTV") or "CTV")
            strategy = str(v_data.get("strategy", "unspecified") or "unspecified")

            # Speed handling: assume YAML 'speed' is km/h; convert to knots
            speed_val = float(v_data.get("speed", 0.0) or 0.0)
            speed_kn = speed_val / 1.852 if speed_val > 0 else 0.0

            # Wave height limit: accept both correct and typo keys
            hs_limit = v_data.get("max_waveheight", v_data.get("max_waveheigh", None))
            Hs_limit_m = float(hs_limit) if hs_limit is not None else 1.5

            # Wind limit (optional)
            wind_limit_ms = v_data.get("max_windspeed", None)
            wind_limit_ms = float(wind_limit_ms) if wind_limit_ms is not None else None

            # Costs & logistics
            mobilization_fee = float(v_data.get("mobilization_cost", 0.0) or 0.0)
            mobilization_days = float(v_data.get("mobilization_days", 0.0) or 0.0)
            port_distance_km = float(v_data.get("port_distance", 0.0) or 0.0)

            out[v_name] = VesselSpec(
                name=v_name,
                capability=capability,
                Hs_limit_m=Hs_limit_m,
                wind_limit_ms=wind_limit_ms,
                speed_kn=speed_kn,
                base_distance_km=port_distance_km,
                strategy=strategy,
                day_rate_eur=equipment_rate,
                mobilization_fee_eur=mobilization_fee,
                mobilization_days=mobilization_days,
            )

        return out




    def _compute_access_profiles(
        self,
        maintenance_specs: List[MaintenanceSpec],
        vessels: Dict[str, VesselSpec],
        p_access_hourly: float = 0.7,   # hardcoded hourly probability of being accessible
    ) -> Dict[Tuple[str, str], AccessProfile]:
        """
        Build access/repair/transit rates per MaintenanceSpec (each failure mode or PM entry).
        Bernoulli windowing: if an L-hour continuous window is required, the success
        probability at any hour is p_access_hourly ** L, so MTTW ≈ 1 / (p_access_hourly ** L),
        and mu_A_per_h = p_access_hourly ** L.

        For option 2 (explicit transit states), we return:
        - mu_T_out_per_h = 1 / t_transit_out
        - mu_R_per_h     = 1 / t_onsite
        - mu_T_back_per_h= 1 / t_transit_back
        and keep service_time_h = t_transit_out + t_onsite + t_transit_back.

        Keying: (component, mode_id) to keep failure modes independent.
        """
        profiles: Dict[Tuple[str, str], AccessProfile] = {}
        for s in maintenance_specs:
            # safe vessel resolution
            v_name = (s.preferred_vessels[0] if s.preferred_vessels else None)
            if not v_name or v_name not in vessels:
                v_name = "CTV" if "CTV" in vessels else next(iter(vessels))
            v = vessels[v_name]

            speed_kmh = 1.852 * v.speed_kn
            t_transit = (v.base_distance_km / speed_kmh) if (speed_kmh > 0 and v.base_distance_km > 0) else 0.0
            t_transit_out = t_transit
            t_transit_back = t_transit
            t_onsite = max(0.0, s.MTTR_h)

            L = t_transit_out + t_onsite + t_transit_back
            L_hrs = int(math.ceil(max(0.0, L)))
            mu_A_per_h = max(1e-12, p_access_hourly ** L_hrs)

            profiles[(s.component, str(s.mode_id))] = AccessProfile(
                task_type=s.task_type,
                mu_A_per_h=mu_A_per_h,
                mu_R_per_h=(1.0 / t_onsite) if t_onsite > 0 else 0.0,
                service_time_h=(t_transit_out + t_onsite + t_transit_back),
                chosen_vessels=[v_name],
            )
        return profiles


    def _turbine_ids(self, windFarm) -> List[str]:
        """Get turbine ids from windFarm. Fallback to a single dummy id.
        TODO: integrate with real WindFarm API.
        """
        try:
            return list(windFarm.turbines.keys())  # type: ignore[attr-defined]
        except Exception:
            return ["T01"]

    def _project_time_index(self) -> Tuple[pd.DatetimeIndex, pd.Timestamp, pd.Timestamp, float]:
        """
        Compute the operational time window and a monthly DatetimeIndex.

        Returns
        -------
        idx : pd.DatetimeIndex
            Monthly timestamps (month starts) covering the operational window.
        op_start_ts : pd.Timestamp
            Absolute timestamp when the operational phase begins.
        op_end_ts : pd.Timestamp
            Absolute timestamp when the operational phase ends.
        T_h : float
            Total operational duration in hours.
        """
        # --- Retrieve config offsets (hours from project start)
        start_h = getattr(self.env.config, "WF_OperationsStart_h", 0.0)
        end_h   = getattr(self.env.config, "WF_OperationsEnd_h", 0.0)

        # --- Compute absolute timestamps for operational window
        op_start_ts = self.project_start + pd.to_timedelta(start_h, unit="h")
        op_end_ts   = self.project_start + pd.to_timedelta(end_h,   unit="h")

        # --- Total operational duration in hours
        T_h = max(1.0, (op_end_ts - op_start_ts).total_seconds() / 3600.0)

        # --- Snap to month starts and build monthly index
        start_month = op_start_ts.to_period("M").start_time
        end_month   = op_end_ts.to_period("M").start_time
        idx = pd.date_range(start=start_month, end=end_month, freq="MS")

        return idx, op_start_ts, op_end_ts, T_h



    def _even_payment_schedule(self, total_opex_eur: float, idx: pd.DatetimeIndex) -> pd.DataFrame:
        per = np.repeat(total_opex_eur / len(idx), len(idx))
        return pd.DataFrame({"timestamp": idx, "OM_payment": per})

    # --------------------------- Mode 1: CAPEX fraction (existing) ---------------------------
    def _calc_opex_as_fraction_of_capex(self) -> Dict[str, Any]:
        """Legacy/simple mode: OpEx as a fraction of CapEx.
        Expects config keys:
          - 'OM_FractionOfCapex': 0..1
          - 'CapEx_Total': numeric (or derived elsewhere)
        """
        om_frac = float(getattr(self.config, "OM_FractionOfCapex", 0.03))
        capex_total = float(getattr(self.config, "CapEx_Total", 1.0e9))
        total_opex = om_frac * capex_total

        idx = self._project_time_index()
        opex_df = self._even_payment_schedule(total_opex, idx)

        # Dummy availability (unchanged legacy behaviour); caller may override
        availability_summary = AvailabilitySummary(
            component_A={}, turbine_A={}, farm_A=0.93, downtime_h={}
        )
        return {
            "mode": "capex_fraction",
            "OPEX_records": opex_df,
            "availability_summary": availability_summary,
            "availability_profile": None,
            "activity_log": None,
            "OpEx_breakdown": OpExBreakdown(
                fixed_OM_eur=total_opex, CM_cost_eur=0.0, PM_cost_eur=0.0, transport_eur=0.0, labour_eur=0.0, spares_eur=0.0,
            ),
        }

    # --------------------------- Mode 2: Analytical CTMC ---------------------------
    def _calc_opex_analytic_ctmc(self) -> Dict[str, Any]:
        maint_specs = self._load_maintenance_specs()
        vessels = self._load_vessels()
        access = self._compute_access_profiles(maint_specs, vessels, p_access_hourly=0.7)

        windFarm = getattr(self.env, "windFarm", None)
        t_ids = self._turbine_ids(windFarm) if windFarm is not None else ["T01"]

        idx, op_start_ts, op_end_ts, T_h = self._project_time_index()

        downtime_h: Dict[str, float] = {}
        comp_mode_A: Dict[str, List[float]] = {}

        # ---- new dict to accumulate component-level costs
        component_costs: Dict[str, Dict[str, float]] = {}

        transport_total = labour_total = spares_total = 0.0
        transport_cm = labour_cm = spares_cm = 0.0
        transport_pm = labour_pm = spares_pm = 0.0

        n_turbines = max(1, len(t_ids))

        for s in maint_specs:
            ap = access[(s.component, str(s.mode_id))]
            t_service = ap.service_time_h
            mu_A = ap.mu_A_per_h
            mu_R = (1.0 / t_service) if t_service > 0 else 0.0

            # ---- rate for this mode
            if s.task_type == "CM":
                lam = s.lambda_per_h
                N_per_turbine = lam * T_h
            else:
                lam = (1.0 / s.tau_h) if s.tau_h else 0.0
                N_per_turbine = (T_h / s.tau_h) if s.tau_h else 0.0

            # ---- 3-state CTMC availability
            if mu_A > 0 and mu_R > 0:
                A_mode = (mu_A * mu_R) / (mu_A * mu_R + lam * (mu_R + mu_A)) if lam > 0 else 1.0
            else:
                A_mode = 0.0 if lam > 0 else 1.0

            comp_mode_A.setdefault(s.component, []).append(A_mode)
            total_downtime_comp = (1.0 - A_mode) * T_h * n_turbines
            downtime_h[s.component] = downtime_h.get(s.component, 0.0) + total_downtime_comp

            # ---- costs
            v = vessels[ap.chosen_vessels[0]]
            cost_transport = v.day_rate_eur * (t_service / 24.0)
            cost_labour    = s.labour_rate_eur_h * s.labour_h
            cost_spares    = s.spares_eur

            N_farm = N_per_turbine * n_turbines
            this_event_transport = N_farm * cost_transport
            this_event_labour    = N_farm * cost_labour
            this_event_spares    = N_farm * cost_spares
            this_event_total     = this_event_transport + this_event_labour + this_event_spares

            # accumulate global totals
            transport_total += this_event_transport
            labour_total    += this_event_labour
            spares_total    += this_event_spares

            if s.task_type == "CM":
                transport_cm += this_event_transport
                labour_cm    += this_event_labour
                spares_cm    += this_event_spares
            else:
                transport_pm += this_event_transport
                labour_pm    += this_event_labour
                spares_pm    += this_event_spares

            # ---- accumulate per-component costs
            cc = component_costs.setdefault(s.component, {
                "transport_eur": 0.0,
                "labour_eur": 0.0,
                "spares_eur": 0.0,
                "CM_eur": 0.0,
                "PM_eur": 0.0,
                "total_eur": 0.0,
            })
            cc["transport_eur"] += this_event_transport
            cc["labour_eur"]    += this_event_labour
            cc["spares_eur"]    += this_event_spares
            cc["total_eur"]     += this_event_total
            if s.task_type == "CM":
                cc["CM_eur"] += this_event_total
            else:
                cc["PM_eur"] += this_event_total

        # ---- Component availability (product of mode availabilities)
        component_A: Dict[str, float] = {}
        for comp, A_list in comp_mode_A.items():
            A_comp = 1.0
            for A_m in A_list:
                A_comp *= A_m
            component_A[comp] = A_comp
        for comp in downtime_h.keys():
            component_A.setdefault(comp, 1.0)

        # ---- Turbine / farm availability
        A_turb = np.prod(list(component_A.values())) if component_A else 1.0
        turbine_A = {tid: A_turb for tid in t_ids}
        farm_A = float(A_turb)

        # ---- OpEx totals
        fixed_om = float(getattr(self.config, "Fixed_OM_Annual", 0.0)) * (T_h / 8760.0)
        cm_cost = transport_cm + labour_cm + spares_cm
        pm_cost = transport_pm + labour_pm + spares_pm
        transport = transport_total
        labour = labour_total
        spares = spares_total
        total = transport + labour + spares + fixed_om

        # ---- Calendarize: build DataFrame and integrate component-level costs
        idx, _, _, _ = self._project_time_index()
        opex_df = self._even_payment_schedule(total, idx)

        # Add per-component cost columns (evenly distributed across months)
        for comp, costs in component_costs.items():
            comp_total = costs.get("total_eur", 0.0)
            per_month = comp_total / len(opex_df) if len(opex_df) > 0 else 0.0
            opex_df[f"{comp}_cost"] = per_month

        # Optionally also include fixed OM per month
        opex_df["fixed_OM"] = fixed_om / len(opex_df) if len(opex_df) > 0 else 0.0

        return {
            "mode": "analytic_ctmc",
            "OPEX_records": opex_df,
            "availability_summary": AvailabilitySummary(
                component_A=component_A,
                turbine_A=turbine_A,
                farm_A=farm_A,
                downtime_h=downtime_h,
            ),
            "availability_profile": self._monthly_availability_profile(idx, farm_A),
            "activity_log": None,
            "OpEx_breakdown": OpExBreakdown(
                fixed_OM_eur=fixed_om,
                CM_cost_eur=cm_cost,
                PM_cost_eur=pm_cost,
                transport_eur=transport,
                labour_eur=labour,
                spares_eur=spares,
            ),
            "component_cost_breakdown": component_costs,
        }



    def _monthly_availability_profile(self, idx: pd.DatetimeIndex, farm_A: float) -> pd.DataFrame:
        return pd.DataFrame({"timestamp": idx, "availability": np.repeat(farm_A, len(idx))})


    # --------------------------- Mode 3: Time-marching CTMC ---------------------------
    def _calc_opex_time_march(self) -> Dict[str, Any]:
        """
        Time-marching CTMC:
        - build per-(turbine, component) CTMCs
        - sample events forward in (continuous) time
        - log activities + costs
        - aggregate to monthly OPEX and availability

        This is a skeleton – fill in TODOs with real sampling, metocean, and dispatch logic.
        """
        # 1) Inputs / setup -----------------------------------------------------------
        maint_specs = self._load_maintenance_specs()
        vessels     = self._load_vessels()

        windFarm = getattr(self.env, "windFarm", None)
        t_ids    = self._turbine_ids(windFarm) if windFarm is not None else ["T01"]

        # project time window
        idx, op_start_ts, op_end_ts, T_h = self._project_time_index()
        sim_end_ts = op_end_ts

        # 2) Build CTMC entities ------------------------------------------------------
        # One entity per (turbine, maintenance spec) for now
        # later you can aggregate per component if needed
        entities = []  # list of dicts or small structs
        for tid in t_ids:
            for s in maint_specs:
                # resolve access profile (gives us mu_A and service_time)
                ap = self._compute_access_profiles([s], vessels).get((s.component, str(s.mode_id)))
                if ap is None:
                    continue

                entity = {
                    "turbine_id": tid,
                    "component": s.component,
                    "mode_id": str(s.mode_id),
                    "task_type": s.task_type,    # "CM" or "PM"

                    # CTMC state
                    "state": "W",                 # W, WA, R
                    "last_change_ts": op_start_ts,

                    # rates (can be made time-dependent later)
                    "lambda_h": s.lambda_per_h if s.task_type == "CM" else (1.0 / s.tau_h if s.tau_h else 0.0),
                    "mu_A_h": ap.mu_A_per_h,
                    "mu_R_h": (1.0 / ap.service_time_h) if ap.service_time_h > 0 else 0.0,

                    # cost params
                    "service_time_h": ap.service_time_h,
                    "preferred_vessels": ap.chosen_vessels or ["CTV"],
                    "labour_rate_eur_h": s.labour_rate_eur_h,
                    "labour_h": s.labour_h,
                    "spares_eur": s.spares_eur,

                    # accounting
                    "time_in_state": {
                        "W": 0.0,
                        "WA": 0.0,
                        "R": 0.0,
                    },
                }
                entities.append(entity)

        # 3) Event list / priority queue ---------------------------------------------
        # For the skeleton we just use a python list; replace with heapq in real code
        # Each event: {"time": ts, "entity_idx": i, "transition": "..."}
        event_queue = []

        # initialize first events per entity (TODO: real sampling)
        for i, ent in enumerate(entities):
            # TODO: sample next event time from current rates and push to queue
            # placeholder: everyone gets an event at op_start_ts
            event_queue.append({
                "time": op_start_ts,
                "entity_idx": i,
                "transition": None,  # to be decided at execution time
            })

        # 4) Activity log (final output) ----------------------------------------------
        activity_rows: List[ActivityLogEntry] = []

        # 5) Turbine-level availability tracking -------------------------------------
        # we track how many components are down per turbine
        turbine_down_counter = {tid: 0 for tid in t_ids}
        turbine_last_change  = {tid: op_start_ts for tid in t_ids}
        turbine_time_up      = {tid: 0.0 for tid in t_ids}
        turbine_time_down    = {tid: 0.0 for tid in t_ids}

        # 6) Main simulation loop -----------------------------------------------------
        current_ts = op_start_ts
        # NOTE: replace this while with proper heap pop logic
        while event_queue and current_ts < sim_end_ts:
            # pick next event (TODO: pop from heap by time)
            evt = event_queue.pop(0)
            evt_ts = evt["time"]
            if evt_ts > sim_end_ts:
                break

            # advance global time
            prev_ts = current_ts
            current_ts = evt_ts
            dt = (current_ts - prev_ts).total_seconds() / 3600.0  # h

            # between prev_ts and current_ts, everyone stayed in their current state
            for ent in entities:
                state = ent["state"]
                ent["time_in_state"][state] += dt

            # also update turbine up/down time
            for tid in t_ids:
                if turbine_down_counter[tid] > 0:
                    turbine_time_down[tid] += dt
                else:
                    turbine_time_up[tid] += dt

            # process this event ------------------------------------------------------
            ent = entities[evt["entity_idx"]]

            # TODO: decide which transition fires, based on ent["state"] and rates
            # For skeleton: force a W -> WA -> R -> W cycle
            old_state = ent["state"]
            if old_state == "W":
                new_state = "WA"
            elif old_state == "WA":
                new_state = "R"
            else:
                new_state = "W"

            ent["state"] = new_state
            ent["last_change_ts"] = current_ts

            # if this transition corresponds to doing maintenance, log activity
            if old_state == "WA" and new_state == "R":
                # build activity row from ent and current_ts
                v_name = ent["preferred_vessels"][0]
                v = vessels.get(v_name, None)
                transport_eur = (v.day_rate_eur * (ent["service_time_h"] / 24.0)) if v else 0.0
                labour_eur    = ent["labour_rate_eur_h"] * ent["labour_h"]
                spares_eur    = ent["spares_eur"]
                total_eur     = transport_eur + labour_eur + spares_eur

                act = ActivityLogEntry(
                    timestamp_start=current_ts,
                    timestamp_end=current_ts + pd.Timedelta(hours=ent["service_time_h"]),
                    turbine_id=ent["turbine_id"],
                    component=ent["component"],
                    task_type=ent["task_type"],
                    vessels=[v_name],
                    sailing_h=0.0,     # TODO
                    onsite_h=ent["service_time_h"],
                    crew_h=ent["labour_h"],
                    spares_eur=spares_eur,
                    labour_eur=labour_eur,
                    transport_eur=transport_eur,
                    total_cost_eur=total_eur,
                )
                activity_rows.append(act)

            # update turbine down-counter if this component changed up/down
            tid = ent["turbine_id"]
            if old_state == "W" and new_state != "W":
                turbine_down_counter[tid] += 1
            elif old_state != "W" and new_state == "W":
                turbine_down_counter[tid] = max(0, turbine_down_counter[tid] - 1)

            # schedule next event for this entity (TODO: real sampling from rates)
            next_evt_ts = current_ts + pd.Timedelta(hours=24.0)  # placeholder
            if next_evt_ts < sim_end_ts:
                event_queue.append({
                    "time": next_evt_ts,
                    "entity_idx": evt["entity_idx"],
                    "transition": None,
                })

        # 7) Build activity log DataFrame --------------------------------------------
        activity_log_df = pd.DataFrame([a.__dict__ for a in activity_rows]) if activity_rows else pd.DataFrame(
            columns=[f.name for f in dataclasses.fields(ActivityLogEntry)]  # type: ignore
        )

        # 8) Aggregate to monthly OPEX ------------------------------------------------
        if not activity_log_df.empty:
            opex_df = (
                activity_log_df
                .assign(month=lambda d: d["timestamp_start"].values.astype("datetime64[M]"))
                .groupby("month", as_index=False)["total_cost_eur"].sum()
                .rename(columns={"month": "timestamp", "total_cost_eur": "OM_payment"})
            )
        else:
            opex_df = pd.DataFrame({"timestamp": idx, "OM_payment": np.zeros(len(idx))})

        # add fixed OM evenly
        fixed_om_total = float(getattr(self.config, "Fixed_OM_Annual", 0.0)) * (len(idx) / 12.0)
        fixed_df = self._even_payment_schedule(fixed_om_total, idx)
        opex_df = (
            pd.concat([opex_df, fixed_df], ignore_index=True)
            .groupby("timestamp", as_index=False)["OM_payment"].sum()
            .sort_values("timestamp")
        )

        # 9) Availability outputs -----------------------------------------------------
        # per component (expected): time_in_state["W"] / total
        component_A = {}
        downtime_h = {}
        total_sim_h = (sim_end_ts - op_start_ts).total_seconds() / 3600.0
        for ent in entities:
            up_h = ent["time_in_state"]["W"]
            A = up_h / total_sim_h if total_sim_h > 0 else 1.0
            component_A[ent["component"]] = max(component_A.get(ent["component"], 0.0), A)
            downtime_h[ent["component"]] = total_sim_h - up_h

        # turbine availability from accumulated times
        turbine_A = {}
        for tid in t_ids:
            up_h = turbine_time_up[tid]
            A = up_h / total_sim_h if total_sim_h > 0 else 1.0
            turbine_A[tid] = A
        farm_A = float(np.mean(list(turbine_A.values()))) if turbine_A else 1.0

        availability_series = pd.DataFrame({"timestamp": idx, "availability": np.repeat(farm_A, len(idx))})

        # 10) Return artefacts --------------------------------------------------------
        return {
            "mode": "time_march_ctmc",
            "OPEX_records": opex_df,
            "availability_summary": AvailabilitySummary(
                component_A=component_A,
                turbine_A=turbine_A,
                farm_A=farm_A,
                downtime_h=downtime_h,
            ),
            "availability_profile": availability_series,
            "activity_log": activity_log_df,
            "OpEx_breakdown": OpExBreakdown(
                fixed_OM_eur=fixed_om_total,
                CM_cost_eur=np.nan,
                PM_cost_eur=np.nan,
                transport_eur=np.nan,
                labour_eur=np.nan,
                spares_eur=np.nan,
            ),
        }


def load_OMData(config):
    """
    Loads wind farm input parameters from the configuration file.
    """
    OM_inputs = {}
    if hasattr(config, 'Opex_inputFiles'):
        for identifier, file_name in config.Opex_inputFiles.items():
            OM_inputs[identifier] = load_yaml(config.valuewind_inputFolder, file_name)
            OM_inputs[identifier] = process_duration_fields(OM_inputs[identifier])
    return OM_inputs


