# =============================================================================
# technical_output.py -- Auto-generated by export_for_lca.py
# Do not edit manually. Re-run export_for_lca.py to update.
# =============================================================================

N_TURBINES              = 34      # int   -- Number of turbines
MW_PER_TURBINE          = 22.0     # float -- Rated capacity per turbine (MW)
TOTAL_FARM_SIZE_MW      = 748.0   # float -- Total installed capacity (MW)
CAPACITY_FACTOR         = 0.53   # float -- Capacity factor (e.g. 0.53)
DISTANCE_TO_SHORE_KM    = 110.0   # float -- Distance to shore (km); inferred from CAPEX.yaml -- Export_cable_supply_offshore_220kV comment: '110 km x 2.5 M EUR/km'
LIFETIME_YEARS          = 20      # int   -- Project lifetime (years); WF_OperationsEnd - WF_OperationsStart (23 - 3)
ENERGY_NET_KWH          = 6.945629e+10  # float -- Net energy over lifetime (kWh)

# All masses converted from tonnes (source) to kg (multiply by 1000)
MASSES_KG = {
    "hub_system":               216646.7,    # CAPEX.yaml: Hub_system fixed materials (121.0 t) + DTU pitch_bearings (95.647 t, formula: 500 + 0.07*D^2.5 kg, D=284 m from iea_22s.py)
    "blades":                   249403.0,  # CAPEX.yaml: 3_blades comment (246.903 t) + blade_surface_coatings.Gelcoat_resin (2.5 t)
    "main_shaft_and_bearings":  59100.0,    # CAPEX.yaml: CARB upwind bearing (42.6 t) + SRB downwind bearing (12.4 t) + main shaft (4.1 t)
    "generator":                504990.0,  # CAPEX.yaml: NdFeB (25.2 t) + Cu (17.1 t) + electrical steel (105.6 t) + structural steel (357.09 t)
    "brake":                    39200.0,    # CAPEX.yaml: Brake.Steel
    "turret":                   6000.0,    # CAPEX.yaml: Turret.Steel
    "bedplate":                 75100.0,    # CAPEX.yaml: Bedplate.Steel
    "yaw_system":               37500.0,    # CAPEX.yaml: Yaw_system.Steel (includes friction plate + motors)
    "nacelle_cover_platforms":  59200.0,    # CAPEX.yaml: Composite_panel (17.8 t) + Steel (41.4 t)
    "hvac_auxiliaries":         19300.0,    # CAPEX.yaml: HVAC_pack (12.8 t) + Cabling_internal (4.0 t) + Lube_and_hydraulics (2.5 t)
    "converter":                17400.0,    # CAPEX.yaml: Converter.Power_electronics_modules
    "transformer":              44000.0,    # CAPEX.yaml: Transformer.Transformer_unit
    "tower":                    1574000.0,  # CAPEX.yaml: Tower.Steel (subsubcategory of Turbine.Substructure)
    "monopile":                 2097000.0,  # CAPEX.yaml: Monopile.Steel (BoP Substructure)
    "transition_piece":         100000.0,   # CAPEX.yaml: Transition_piece.Steel (BoP Substructure)
}

# N_interventions for failure mode_id == 3 per component
# Source: OPEX analytic_ctmc simulation (OM_22MW.yaml / OPEX.yaml)
N_INTERVENTIONS_MODE3 = {
    "power converter":    58.721934,
    "electrical system":    1.525591,
    "hydraulic pitch system":    0.706549,
    "yaw_system":    0.706549,
    "rotor_blades":    0.889081,
    "generator":    6.865150,
    "drive_train":    7.411686,
}

# Expected vessel hours over the operational lifetime, summed by vessel type
# Source: OPEX analytic_ctmc simulation -- vessel_records[summary_by_vessel]
VESSEL_HOURS_BY_TYPE = {
    "CTV":    48925.59,
    "LCN":    30914.33,
}
